/**
 * Re-exports of Kit errors commonly used in transaction building.
 *
 * @packageDocumentation
 */

import {
  isSolanaError,
  SOLANA_ERROR__TRANSACTION__FEE_PAYER_MISSING,
  SOLANA_ERROR__TRANSACTION__SIGNATURES_MISSING,
  SOLANA_ERROR__BLOCK_HEIGHT_EXCEEDED,
  SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE,
} from '@solana/errors';

// Re-export isSolanaError for convenience
export { isSolanaError };

// Re-export commonly used Kit error codes
export {
  SOLANA_ERROR__TRANSACTION__FEE_PAYER_MISSING,
  SOLANA_ERROR__TRANSACTION__SIGNATURES_MISSING,
  SOLANA_ERROR__BLOCK_HEIGHT_EXCEEDED,
  SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE,
};

// Convenience aliases for common errors
export const ERROR_FEE_PAYER_MISSING = SOLANA_ERROR__TRANSACTION__FEE_PAYER_MISSING;
export const ERROR_BLOCKHASH_EXPIRED = SOLANA_ERROR__BLOCK_HEIGHT_EXCEEDED;
export const ERROR_SIMULATION_FAILED =
  SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE;



